language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: KaPi9ci2k3taLQ7pX04JBOphdc9YVC4FjdKgNLGEPyAvepPgF8DfZCoBqVTLxd3CqqOfDjFbfs3x1IeHOw03+/YpfE+0l9Yv4vngCcgC/Hmqqp5ioc2VpjnITPH4CtSlYXhR4iwiTiu7aHaPEpFelGIq1ODSQiC7arYvhjfA2Jd1y3zHngh4IW6dUjY7SfGzkfn0PbM/u23UI8bbuMpwV052o2POsHyz6zM5EB4nCTRgtdhmHlnW6u8ol9L7GCjzHofjJpuVJxW/WdzLCJs4ZO1LUL0eMEfxUVQxZShqHkpnU2WAOx4rQpO7Td/Kk03z/SWl3PjeIpehjvbKk2o8Dwrc3aG1b4Qn0voHX/yCgwjOyXH/v0I44eMKxvjJH95f9doSsrqW/tSR/23VwiimSvWa//wfQP9/EXGqlQSa5ow4kAKa8SVxN0hJWwSRq24LzzFiRZ7/etpb85eDwzLplh5O3Llbc96tRoK+H5lKNlmya1IXpDEGUuCxkWDEYReUa5DqHUYJ8KOynQgdH3qnR9OIHjyxgy00npJCt7d1sFtXq9HjhggHlDhhBUDL7w7pvUfS9XTypmYtyI5j+50pRToN8xLgRlXzmEmj3q3C0kX8O5eXESVr3TJL3zkzNMZUv/bfIhAx0pGrVMB2vU7sVDKrEcAyIxEufPtWhifaOEc=
    # FIREBASE_SECRET
    - secure: KZfoUZmBeCQD6sjovQ2ycb0agq9s1WVLzOnLexHFJCOpcR+7rvINC50uQ08wxN9oD32UkeusGK1QhaJ1LDqL9HlQF5iEcyvEXjfF8BdoAOr626E3XJBzwnMl/oFJZpwSjSbBYFW18SY+Lb3t24bf8msU3OXATQzhObvj8KycvFk8hvbTxmap++5J+oP5y/u93gzko3ZJcm/EWSHlf4unuOyTj8MZmF7PljZ4EssKeyRwkQlnjoiMIKQB6HN6+ZYOWBlOWWjK8c9P2j6wMBh0gV3p/R9Mj2rMIfXslH34wVuGEW12BWfZRjfyaWndzVnw2bx1ZwTWlXCaaD1bjQJN7OkQrjWxd5BdfXNSsSBVoQXIVDDH+hb2Y1/cYw7A1IY08K7BEY97CBVNM4LVl3RcPGe6FPvLY+Q1cRCzo17Uf/NubTmONQXsWLYIMb1C5MCP/ydUYQ2gy4dVqLOkhY4zvjYi5YZ9eMQv9fMwENBVBUQN0xEPiH88Iy3ZY7AObT2o3xDr0QTkkFcbmukM9qOw/DCvsWM6t9fJybKgT8VHLxakAcLrM3vrBgiY9wsoWxG5GfWCCPJDItILbsfMRd65G1T/3b0h2ubTN5KicP0YKgLPWswjx+kAFoMeOqCqUCEqGy3A2tMUHYLCx9/u2rEX++r7eUbkoXfwxUmuqUmX3ak=
